# Generated by Django 3.1.4 on 2021-06-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
